### PR TITLE
removed the thing

### PR DESCRIPTION
**Pull request by mollyMillion4**

### CODE REVIEW

**Comment by CodeCorrupt** [comment]
#1

**Comment by CodeCorrupt** [comment]
ps. I can't figure out how to update a different file in this same pull request.... soooo you should also track down that password I mentioned in #1 (Splunk/SPDeployment.yaml) and remove that too, then add it to this.

**Comment by khodges42** [comment]
+1 lgtm boat boat boat

**Comment by khodges42** [comment]
@CodeCorrupt I think you pull master, checkout autumns branch, delete the file, then commit+push. Not sure if there's a way to do it from github

**Comment by CodeCorrupt** [comment]
@khodges42 Only way I can find is to clone @mollyMillion4's branch, then create a pull request to her repo... it's kinda ridiculous. I may just close this and make a new pull request... but I don't want to steal the commits lol

**Comment by CodeCorrupt** [comment]
Took care of this in another commit. Great comment though!

**Pull request closed without merging**
